#!/usr/bin/env python3
"""Validate the repository harness's synchronization points.

Every check below is a pair of files that must agree and that nothing else
enforces; a failing check names the file to edit. Runs in `just validate`,
in pre-commit, and therefore in CI. Standard library only: the YAML files it
reads are authored in this repository in a fixed shape, and the narrow
readers here fail loudly when that shape changes.

Checks (errors unless marked warning):
  labels     issue forms and dependabot reference only labels in
             .github/labels.json; every label has an applier; catalog/*
             labels, the catalogs on disk, and every form's Catalog options
             agree; priority/* labels and every form's Priority options agree
  template   the PR template carries the related / validation / checklist
             headings, the security checklist line, and a `Spec:` line
  intake     ISSUE_TEMPLATE/config.yml disables blank issues
  pointers   every path AGENTS.md and ARCHITECTURE.md name exists; every
             .agents/knowledge/*.md is named in AGENTS.md; every `just
             <recipe>` AGENTS.md names exists (README: warning)
  copies     scripts/sync_labels.py and scripts/archive_completed_changes.py are byte-identical to their origins in the
             meta-github-workflow skill unless it carries a `# DIVERGENCE:`
             line explaining why
  checks     workflow job names and the table in
             .agents/knowledge/github-checks.md agree in both directions
  openspec   .agents/skills/openspec-* is exactly the core skill set, each
             generated by the CLI version pinned in the justfile, the target
             marker is `agents`, and no file hard-codes the package version
  ruff       the ruff pin agrees across .pre-commit-config.yaml,
             .devcontainer/devcontainer.json, and .github/workflows/checks.yml
             (warning: the pre-commit ruff hooks cover skill scripts)

Exit codes: 0 = all checks pass (warnings allowed), 1 = at least one error,
2 = a required file is unreadable or not in the expected shape.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LABELS = ROOT / ".github" / "labels.json"
FORMS_DIR = ROOT / ".github" / "ISSUE_TEMPLATE"
PR_TEMPLATE = ROOT / ".github" / "PULL_REQUEST_TEMPLATE.md"
DEPENDABOT = ROOT / ".github" / "dependabot.yml"
WORKFLOWS = ROOT / ".github" / "workflows"
CHECKS_DOC = ROOT / ".agents" / "knowledge" / "github-checks.md"
KNOWLEDGE = ROOT / ".agents" / "knowledge"
AGENTS_MD = ROOT / "AGENTS.md"
ARCHITECTURE_MD = ROOT / "ARCHITECTURE.md"
README_MD = ROOT / "README.md"
JUSTFILE = ROOT / "justfile"
PRECOMMIT = ROOT / ".pre-commit-config.yaml"
DEVCONTAINER = ROOT / ".devcontainer" / "devcontainer.json"
CHECKS_WORKFLOW = WORKFLOWS / "checks.yml"
SKILLS_DIR = ROOT / ".agents" / "skills"
OPENSPEC_TARGET = SKILLS_DIR / ".openspec-target"
SYNC_LABELS = ROOT / "scripts" / "sync_labels.py"
SYNC_LABELS_ORIGIN = ROOT / "skills" / "meta" / "meta-github-workflow" / "scripts" / "sync_labels.py"
ARCHIVE_SCRIPT = ROOT / "scripts" / "archive_completed_changes.py"
ARCHIVE_SCRIPT_ORIGIN = (
    ROOT / "skills" / "engineering" / "spec-driven-development" / "scripts" / "archive_completed_changes.py"
)

MANAGED_PREFIXES = ("priority/", "catalog/")
NEEDS_TRIAGE = "status/needs-triage"
APPLIERS = {"form", "triage", "human"}
OPENSPEC_CORE_SKILLS = {
    "openspec-apply-change",
    "openspec-archive-change",
    "openspec-explore",
    "openspec-propose",
    "openspec-sync-specs",
    "openspec-update-change",
}
OPENSPEC_TARGET_VALUE = "agents"
OPENSPEC_CONFIG = ROOT / "openspec" / "config.yaml"
OPENSPEC_SCHEMA = "skill-change"
LABEL_PREFIX_SKIP = ("catalog/", "priority/", "status/", "http")

errors: list[str] = []
warnings: list[str] = []


def error(message: str) -> None:
    errors.append(message)


def warn(message: str) -> None:
    warnings.append(message)


def fail(message: str) -> None:
    print(f"validate_harness: error: {message}", file=sys.stderr)
    sys.exit(2)


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"cannot read {path.relative_to(ROOT)}: {exc}")
    return ""  # unreachable


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


# --- narrow YAML readers -----------------------------------------------------


def yaml_top_level_list(text: str, key: str) -> list[str]:
    """Values of a top-level `key:` block list (`  - value`) or flow list."""
    match = re.search(rf"^{re.escape(key)}:[ \t]*(.*)$", text, re.MULTILINE)
    if not match:
        return []
    rest = match.group(1).strip()
    if rest.startswith("["):
        return [item.strip().strip("\"'") for item in rest.strip("[]").split(",") if item.strip()]
    values = []
    for line in text[match.end() :].splitlines():
        if not line.strip():
            continue
        item = re.match(r"^\s+-\s+(.+?)\s*$", line)
        if item and line.startswith(" "):
            values.append(item.group(1).strip("\"'"))
        else:
            break
    return values


def form_dropdown_options(text: str, label: str) -> list[str] | None:
    """Options of the dropdown whose `label:` equals `label`, or None."""
    blocks = re.split(r"^\s+- type:", text, flags=re.MULTILINE)
    for block in blocks:
        if re.search(rf"^\s+label:\s*{re.escape(label)}\s*$", block, re.MULTILINE):
            match = re.search(r"^\s+options:\s*$\n((?:\s+-\s+.+\n?)+)", block, re.MULTILINE)
            if not match:
                return []
            return [re.sub(r"^\s+-\s+", "", line).strip() for line in match.group(1).splitlines() if line.strip()]
    return None


def dependabot_labels(text: str) -> set[str]:
    labels: set[str] = set()
    for match in re.finditer(r"^\s+labels:\s*\[(.*?)\]\s*$", text, re.MULTILINE):
        labels.update(item.strip().strip("\"'") for item in match.group(1).split(",") if item.strip())
    return labels


def workflow_job_names(path: Path) -> list[str]:
    """`jobs.<id>.name` when present, else `<id>`, per top-level job."""
    text = read(path)
    jobs = re.search(r"^jobs:\s*$\n(.*)", text, re.MULTILINE | re.DOTALL)
    if not jobs:
        fail(f"{rel(path)} has no top-level jobs: block")
    names = []
    for job in re.finditer(r"^  ([A-Za-z0-9_-]+):\s*$\n((?:    .*\n|\s*\n|\s*#.*\n)*)", jobs.group(1), re.MULTILINE):
        name = re.search(r"^    name:\s*(.+?)\s*$", job.group(2), re.MULTILINE)
        names.append(name.group(1).strip("\"'") if name else job.group(1))
    if not names:
        fail(f"{rel(path)}: could not parse any job under jobs:")
    return names


# --- checks ------------------------------------------------------------------


def check_labels() -> None:
    try:
        data = json.loads(read(LABELS))
    except json.JSONDecodeError as exc:
        fail(f"{rel(LABELS)} is not valid JSON: {exc}")
    labels = {}
    for item in data:
        name = str(item.get("name", "")).strip()
        applier = item.get("applied_by")
        if applier not in APPLIERS:
            error(f'{rel(LABELS)}: label {name!r} needs "applied_by" set to one of {sorted(APPLIERS)}.')
        labels[name] = applier

    form_labels: set[str] = set()
    catalog_options: dict[str, list[str]] = {}
    priority_options: dict[str, list[str]] = {}
    for form in sorted(FORMS_DIR.glob("*.yml")):
        if form.name == "config.yml":
            continue
        text = read(form)
        form_labels.update(yaml_top_level_list(text, "labels"))
        for key, store in (("Catalog", catalog_options), ("Priority", priority_options)):
            options = form_dropdown_options(text, key)
            if options is None:
                error(f"{rel(form)}: no dropdown labelled {key!r}; the triage script reads that section.")
            else:
                store[rel(form)] = options
    dep_labels = dependabot_labels(read(DEPENDABOT)) if DEPENDABOT.exists() else set()

    for label in sorted(form_labels | dep_labels):
        if label not in labels:
            error(
                f"label {label!r} is referenced by an issue form or dependabot.yml but missing from {rel(LABELS)}; "
                "GitHub would drop it silently."
            )
    for name, applier in labels.items():
        consumed = (
            name in form_labels
            or name in dep_labels
            or name.startswith(MANAGED_PREFIXES)
            or name == NEEDS_TRIAGE
            or applier == "human"
        )
        if not consumed:
            error(
                f"{rel(LABELS)}: label {name!r} is applied by nothing "
                "(no form, dependabot, triage prefix, or applied_by human)."
            )
        if applier == "form" and name not in form_labels | dep_labels:
            error(f"{rel(LABELS)}: label {name!r} says applied_by form but no form applies it.")
        if applier == "triage" and not (name.startswith(MANAGED_PREFIXES)):
            error(f"{rel(LABELS)}: label {name!r} says applied_by triage but has no managed prefix.")

    catalogs_on_disk = {p.name for p in (ROOT / "skills").iterdir() if p.is_dir()}
    catalog_labels = {n.split("/", 1)[1] for n in labels if n.startswith("catalog/")} - {"repository"}
    if catalog_labels != catalogs_on_disk:
        error(
            f"catalog/* labels in {rel(LABELS)} ({sorted(catalog_labels)}) differ from the catalogs "
            f"under skills/ ({sorted(catalogs_on_disk)})."
        )
    for form, options in catalog_options.items():
        if set(options) - {"repository"} != catalogs_on_disk or "repository" not in options:
            error(f"{form}: Catalog options {options} must be the catalogs under skills/ plus 'repository'.")
    priority_labels = {n.split("/", 1)[1] for n in labels if n.startswith("priority/")}
    for form, options in priority_options.items():
        if set(options) != priority_labels:
            error(f"{form}: Priority options {options} differ from priority/* labels {sorted(priority_labels)}.")


def check_template() -> None:
    text = re.sub(r"<!--.*?-->", "", read(PR_TEMPLATE), flags=re.DOTALL)
    headings = [h.lower() for h in re.findall(r"^## (.+?)\s*$", text, re.MULTILINE)]
    for role in ("related", "validation", "checklist"):
        if not any(role in h for h in headings):
            error(f"{rel(PR_TEMPLATE)}: no '## ' heading contains {role!r}; scripts/check_pr_policy.py needs one.")
    if not re.search(r"^\s*- \[ \].*secrets", text, re.MULTILINE | re.IGNORECASE):
        error(
            f"{rel(PR_TEMPLATE)}: the checklist needs an unticked line containing 'secrets' "
            "(check_pr_policy.py keys on it)."
        )
    if not re.search(r"^Spec:", text, re.MULTILINE):
        error(f"{rel(PR_TEMPLATE)}: needs a 'Spec:' line (see .agents/knowledge/spec-workflow.md).")


def check_intake() -> None:
    config = FORMS_DIR / "config.yml"
    if not re.search(r"^blank_issues_enabled:\s*false\s*$", read(config), re.MULTILINE):
        error(f"{rel(config)}: blank_issues_enabled must be false (questions route to Discussions).")


def path_like(name: str) -> bool:
    if any(ch in name for ch in "<>*{} \"'") or name.startswith(LABEL_PREFIX_SKIP):
        return False
    if re.fullmatch(r"[A-Z/]+", name):
        return False
    return "/" in name or name.startswith(".")


def check_pointers() -> None:
    for doc in (AGENTS_MD, ARCHITECTURE_MD):
        text = read(doc)
        for token in sorted(set(re.findall(r"`([^`\n]+)`", text))):
            if not path_like(token):
                continue
            candidate = token.rstrip("/").split(":")[0]
            if candidate.startswith("../"):
                continue
            if not (ROOT / candidate).exists() and not (ROOT / "skills" / candidate).exists():
                error(f"{rel(doc)} names `{token}`, which does not exist.")
    agents = read(AGENTS_MD)
    for knowledge in sorted(KNOWLEDGE.rglob("*.md")):
        if rel(knowledge) not in agents:
            error(f"{rel(knowledge)} is not named in AGENTS.md; a knowledge file without a pointer is invisible.")
    recipes = set(re.findall(r"^([a-z][a-z0-9-]*)(?:\s+\+?[A-Z_]+)*\s*:(?!=)", read(JUSTFILE), re.MULTILINE))
    for doc, report in ((AGENTS_MD, error), (README_MD, warn)):
        for recipe in set(re.findall(r"`just ([a-z][a-z0-9-]*)", read(doc))):
            if recipe not in recipes:
                report(f"{rel(doc)} names `just {recipe}`, which is not a justfile recipe.")


def check_copies() -> None:
    ours, origin = read(SYNC_LABELS), read(SYNC_LABELS_ORIGIN)
    if ours != origin and "# DIVERGENCE:" not in ours:
        error(
            f"{rel(SYNC_LABELS)} differs from {rel(SYNC_LABELS_ORIGIN)}; copy the origin over it "
            "(run `ruff format` on both) or add a `# DIVERGENCE: <why>` line."
        )
    ours, origin = read(ARCHIVE_SCRIPT), read(ARCHIVE_SCRIPT_ORIGIN)
    if ours != origin:
        error(
            f"{rel(ARCHIVE_SCRIPT)} differs from {rel(ARCHIVE_SCRIPT_ORIGIN)}; copy the origin over it "
            "(the repository runs the skill's script, never a fork of it)."
        )


def check_checks_doc() -> None:
    in_workflows = set()
    for workflow in sorted(WORKFLOWS.glob("*.yml")):
        in_workflows.update(workflow_job_names(workflow))
    doc = read(CHECKS_DOC)
    in_doc = set(re.findall(r"^\| `([^`]+)` \|", doc, re.MULTILINE))
    for name in sorted(in_workflows - in_doc):
        error(f"workflow job {name!r} is not in the table of {rel(CHECKS_DOC)}.")
    for name in sorted(in_doc - in_workflows):
        error(f"{rel(CHECKS_DOC)} lists {name!r} but no workflow job produces it.")


def check_openspec() -> None:
    pin = re.search(r'^openspec_version\s*:=\s*"([^"]+)"', read(JUSTFILE), re.MULTILINE)
    if not pin:
        fail("justfile has no openspec_version variable")
    present = {
        p.name for p in SKILLS_DIR.iterdir() if p.is_dir() and not p.is_symlink() and p.name.startswith("openspec-")
    }
    if present != OPENSPEC_CORE_SKILLS:
        error(
            f".agents/skills/openspec-* is {sorted(present)}, expected {sorted(OPENSPEC_CORE_SKILLS)}; "
            "run `just spec-sync` with the core profile."
        )
    for name in sorted(present & OPENSPEC_CORE_SKILLS):
        text = read(SKILLS_DIR / name / "SKILL.md")
        stamp = re.search(r'^\s+generatedBy:\s*"?([^"\n]+)"?\s*$', text, re.MULTILINE)
        if not stamp or stamp.group(1) != pin.group(1):
            error(
                f".agents/skills/{name}/SKILL.md was generated by {stamp.group(1) if stamp else 'unknown'}, "
                f"justfile pins {pin.group(1)}; run `just spec-sync`."
            )
    if not OPENSPEC_TARGET.exists() or read(OPENSPEC_TARGET).strip() != OPENSPEC_TARGET_VALUE:
        error(f"{rel(OPENSPEC_TARGET)} must contain {OPENSPEC_TARGET_VALUE!r} (the shared .agents/skills target).")
    for path in (CHECKS_WORKFLOW, DEVCONTAINER):
        if "@fission-ai/openspec@" in read(path):
            error(
                f"{rel(path)} hard-codes the OpenSpec version; "
                "use `just install-tools` so the justfile pin is the only copy."
            )
    config = read(OPENSPEC_CONFIG)
    selected = re.search(r"^schema:\s*(\S+)\s*$", config, re.MULTILINE)
    if not selected or selected.group(1) != OPENSPEC_SCHEMA:
        error(f"{rel(OPENSPEC_CONFIG)} must select the project schema `schema: {OPENSPEC_SCHEMA}`.")
    schema_dir = ROOT / "openspec" / "schemas" / OPENSPEC_SCHEMA
    if not (schema_dir / "schema.yaml").exists():
        error(f"{rel(schema_dir)}/schema.yaml is missing; the selected schema has no definition.")
    else:
        for template in re.findall(r"^\s+template:\s*(\S+)\s*$", read(schema_dir / "schema.yaml"), re.MULTILINE):
            if not (schema_dir / "templates" / template).exists():
                error(f"{rel(schema_dir)}/schema.yaml names template {template!r} but templates/{template} is missing.")
    if re.search(r"^rules:", config, re.MULTILINE):
        error(f"{rel(OPENSPEC_CONFIG)} carries a `rules:` block; artifact rules live in {rel(schema_dir)}/schema.yaml.")


def check_ruff() -> None:
    precommit = read(PRECOMMIT)
    hook = re.search(r"ruff-pre-commit\s*\n\s*rev:\s*v?([0-9.]+)", precommit)
    container = re.search(r"ruff==([0-9.]+)", read(DEVCONTAINER))
    ci = re.search(r"ruff==([0-9.]+)", read(CHECKS_WORKFLOW))
    versions = {
        rel(PRECOMMIT): hook.group(1) if hook else None,
        rel(DEVCONTAINER): container.group(1) if container else None,
        rel(CHECKS_WORKFLOW): ci.group(1) if ci else None,
    }
    if len(set(versions.values())) != 1 or None in versions.values():
        error(f"ruff pins disagree: {versions}; set the same version in all three files.")
    files_re = re.search(r"- id: ruff(?:-check)?\s*\n\s*files:\s*(\S+)", precommit)
    if not files_re or not re.match(files_re.group(1), "skills/core/x/scripts/y.py"):
        warn(f"{rel(PRECOMMIT)}: the ruff hook's files pattern does not cover skill scripts (skills/*/*/scripts).")


def main() -> int:
    for check in (
        check_labels,
        check_template,
        check_intake,
        check_pointers,
        check_copies,
        check_checks_doc,
        check_openspec,
        check_ruff,
    ):
        check()
    for message in warnings:
        print(f"WARNING: {message}")
    for message in errors:
        print(f"ERROR: {message}")
    if errors:
        print(
            f"validate_harness: {len(errors)} error(s). "
            "Sources of truth: .github/labels.json, the PR template, the justfile, AGENTS.md.",
            file=sys.stderr,
        )
        return 1
    print("OK: harness synchronization checks passed.")
    return 0


if __name__ == "__main__":
    if (
        subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, cwd=ROOT).returncode
        != 0
    ):
        fail("not inside a git checkout")
    sys.exit(main())
